import requests
from bs4 import BeautifulSoup

headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '3600',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'
    }


udemy_links_array=["'https://www.udemy.com/course/theabcdmethod/?couponCode=34493316E27B06BF0CFB', 'https://www.udemy.com/course/monta-sitios-web-con-wordpress-en-tu-propio-vps-con-vestacp-optimizado/?couponCode=968D3115EB7DD3E1FC8D', 'https://www.udemy.com/course/iso-45001-2018-complete-course/?couponCode=4599D635E64FD35B297B', 'https://www.udemy.com/course/passive-income-make-money-online/?couponCode=GIFT2020X', 'https://www.udemy.com/course/accounting-for-entrepreneurs/?couponCode=BFB6A4EDE446DDF25727', 'https://www.udemy.com/course/facebook-ads-marketing-hindi-urdu-targeting-strategies-2021-2022-2020/?couponCode=12NOV2020', 'https://www.udemy.com/course/content-marketing-course-2021/?couponCode=TOP111', 'https://www.udemy.com/course/the-badass-entrepreneur-1-manifest-your-mission/?couponCode=396D6A511A88EE4EA11F', 'https://www.udemy.com/course/sage-nein-ohne-zu-verletzen-fuhle-dich-selbstbewusst/?couponCode=NEINSTART', 'https://www.udemy.com/course/sifre-guvenligi-sosyal-medya/?couponCode=2020BITIS', 'https://www.udemy.com/course/android-telefon-ve-tabletleri-hackleme/?couponCode=2020BITIS', 'https://www.udemy.com/course/trabalhar-com-ti-no-exterior/?couponCode=DD07959FAF5CD086079F'",
"'https://www.udemy.com/course/introduction-to-computer-science-with-python/?couponCode=D3E944C272875308529D', 'https://www.udemy.com/course/cofounding-the-right-way/?couponCode=NOVEMBERGIFT', 'https://www.udemy.com/course/personal-business-development-for-startup-founders/?couponCode=NOVEMBERGIFT', 'https://www.udemy.com/course/tikker-lingua-discover-german-dialects/?couponCode=E204E94BCF8CB111A42C', 'https://www.udemy.com/course/industry-4-complete-guide/?couponCode=INDUSTRY11', 'https://www.udemy.com/course/management-consulting-skill/?couponCode=FREEEN', 'https://www.udemy.com/course/management-consulting-strategy/?couponCode=FREEEN', 'https://www.udemy.com/course/daytrading/?couponCode=1NOV20', 'https://www.udemy.com/course/facebook-ppc/?couponCode=TOP111111', 'https://www.udemy.com/course/complete-photography-course/?couponCode=PHOTO9IN1NOV2020', 'https://www.udemy.com/course/python-and-flask-only-demonstration-course/?couponCode=9A8C8BBD15AE6B547376', 'https://www.udemy.com/course/python-for-beginners-course-in-depth/?couponCode=B1E815983D38C6A4715A'",
"'https://www.udemy.com/course/facebook-ads-facebook-marketing-strategy-advertising-for-traffic/?couponCode=12NOV2020', 'https://bit.ly/35oISNx', 'https://www.udemy.com/course/autocad-2020-for-designers-a-problem-solving-approach/?couponCode=SWITCHTOCAD', 'https://www.udemy.com/course/learning-solidworks-for-students-engineers-and-designers/?couponCode=WORLDOFDESIGN', 'https://www.udemy.com/course/ptsd-veteran-trauma-cbt-life-coaching-course/?couponCode=VETERANS', 'https://www.udemy.com/course/reportes-dinamicos-en-excel-power-query-power-pivot-dax/?couponCode=51362A8D012D9B8EF3AA', 'https://www.udemy.com/course/csharp-fundamentals/?couponCode=EFBA7982021978C9539E', 'https://www.udemy.com/course/optimization-in-python/?couponCode=PYOMONOV', 'https://www.udemy.com/course/introduction-3-d-secure-3ds-2-in-digital-payments-anythingfinanceorg/?couponCode=ANYTHINGFINANCE.ORG', 'https://www.udemy.com/course/learn-to-make-money-on-youtube/?couponCode=85A63A5F53D2DAA5B216', 'https://www.udemy.com/course/2021-advanced-python/?couponCode=65BC0BAFD93AE9EE3552', 'https://www.udemy.com/course/microsoft-word-expert/?couponCode=DRCOURSEUDEMY'"]


""",
"'https://www.udemy.com/course/the-complete-beginners-guide-to-the-arduino/?couponCode=27CCD9DC12A6C6BC8219', 'https://www.udemy.com/course/2021-machine-learning-from-scratch-python/?couponCode=4213508B95FF472BB201', 'https://www.udemy.com/course/sakshieconomicsart-therapycovid/?couponCode=ECONOMICS', 'https://www.udemy.com/course/getting-started-with-microsoft-excel/?couponCode=62A6B0334EE90240AD3D', 'https://www.udemy.com/course/confidencesolution/?couponCode=BFDAYFREE', 'https://www.udemy.com/course/ecommercewebsite/?couponCode=BFDAYFREE', 'https://www.udemy.com/course/weka30mins/?couponCode=B823927D389567757AD3', 'https://www.udemy.com/course/germanclearandheartfull/?couponCode=0EDD1218FB1139002607', 'https://www.udemy.com/course/children-and-parenting-confidence-course-motivation/?couponCode=PARENTS', 'https://www.udemy.com/course/microsoft-excel-basic-excel-advanced-excel-formulas/?couponCode=5F150BE5C5D847A1DE01', 'https://www.udemy.com/course/introduction-to-the-basics-of-melt-pour-soap/?couponCode=76C57821ADED3AD47E47', 'https://bit.ly/3eQySiS'",
"'https://www.udemy.com/course/intro-to-basic-video-creation/?couponCode=3342515E886C8CFC53C0', 'https://www.udemy.com/course/projelere-doyamayacaksiniz-php-pdo-html-html5-css-js/?couponCode=YENIDENPROGRAMLA', 'https://www.udemy.com/course/color-theory-basics-learning-color-theory-with-adobe-color/?couponCode=85F82C3B9C96FBEFFCC4', 'https://www.udemy.com/course/a-frame-framework/?couponCode=TRY10FREE404', 'https://www.udemy.com/course/the-complete-css-course/?couponCode=TRY10FREE404', 'https://www.udemy.com/course/the-complete-html-5-course-from-scratch/?couponCode=TRY10FREE404', 'https://www.udemy.com/course/certified-kubernetes-administrator-course/?couponCode=TRY10FREE404', 'https://www.udemy.com/course/ultimate-ethical-hacking/?couponCode=FREE4HACKERS', 'https://www.udemy.com/course/sapob52okp1/?couponCode=FAF1AAA04627DE78AAFC', 'https://www.udemy.com/course/agile-scrum-in-depth-guide-simulation-and-best-practices/?couponCode=DA34D463FC3C328F4103', 'https://www.udemy.com/course/r-programming-course-for-absolute-beginners/?couponCode=EVALUATION', 'https://www.udemy.com/course/advanced-functions-a-complete-course-on-precalculus/?couponCode=AA867113ACD8640154F4'",
"'https://www.udemy.com/course/network-protocol-ethical-hacking-course/?couponCode=HULAKK', 'https://www.udemy.com/course/learn-and-understand-buffer-overflow-from-scratch-beginner/?couponCode=BFPU12', 'https://bit.ly/2UiTh72', 'https://www.udemy.com/course/learn-and-understand-ethical-hacking-from-scratch/?couponCode=58-ERT', 'https://www.udemy.com/course/estimation-fundamentals/?couponCode=8CF25514C2FEF0ED614A', 'https://www.udemy.com/course/chronic-illness-fatigue/?couponCode=YGTHEXPNOV132020', 'https://www.udemy.com/course/-affiliate-marketing-step-by-step-blueprint/?couponCode=927295B1BEDCAF8E8A9F', 'https://www.udemy.com/course/complete-vmware-vsphere-esxi-and-vcenter-administration/?couponCode=ONETIMEONLY', 'https://www.udemy.com/course/learn-html-in-a-weekend/?couponCode=LEARN_HTML_007', 'https://www.udemy.com/course/certified-financial-manager-diplomain-arabic/?couponCode=D4E9ECAC369D45D4EFAD', 'https://www.udemy.com/course/easy-learning-c-for-beginners/?couponCode=997232B6356082E41670', 'https://www.udemy.com/course/preparing-financial-statements/?couponCode=B67364552C62B2E01466'",
"'https://www.udemy.com/course/financial-analysis-in-arabic/?couponCode=6FE720EACB37986BEDCF', 'https://www.udemy.com/course/international-financial-reporting-standards-ifrs-k/?couponCode=FC3C5ED2EAC58956D770', 'https://www.udemy.com/course/preparing-budgets-in-arabic/?couponCode=3A945291900E190EA732', 'https://www.udemy.com/course/the-complete-introduction-to-the-deep-web/?couponCode=DF8527E5D38DAEB4B6B5', 'https://bit.ly/3nfOUWu', 'https://www.udemy.com/course/work-home-transcription-jobs/?couponCode=2816190E29BDD1F5B7ED', 'https://www.udemy.com/course/curso-microsoft-power-bi/?couponCode=NOV20-1', 'https://www.udemy.com/course/mastering-coding-interviews-and-competitions/?couponCode=ALGOSTEMFREE', 'https://www.udemy.com/course/learn-how-to-create-and-make-jewellery-the-basics-in-design/?couponCode=JOINVICKY', 'https://www.udemy.com/course/php-registration-form-email-confirmation-responsive-email/?couponCode=2AB585211BAA51C0B727', 'https://www.udemy.com/course/learn-python-programming-from-a-z/?couponCode=32864F3DAC3F7534AF84', 'https://www.udemy.com/course/microsoft-excel-intermedio/?couponCode=0F47FC71026380C1ED3F'",
"'https://www.udemy.com/course/complete-french-course/?couponCode=FRENCHCOURSEFORFREE', 'https://www.udemy.com/course/power-query-masterclass/?couponCode=LAUNCH', 'https://www.udemy.com/course/certified-lean-six-sigma-black-belt-training-e/?couponCode=BLACK9', 'https://www.udemy.com/course/hr-analytics-course-with-r/?couponCode=ANALYTICS10', 'https://www.udemy.com/course/advanced-cyber-security-malware-hacking-course/?couponCode=JONAJ1A', 'https://www.udemy.com/course/python-for-absolute-beginners-april-2020-edition/?couponCode=17-QQWA', 'https://www.udemy.com/course/cyber-security-kali-linux-course/?couponCode=IGNA128', 'https://www.udemy.com/course/the-certified-ethical-hackingceh-course-2020/?couponCode=BKVETA', 'https://www.udemy.com/course/color-grading-and-video-editing-with-davinci-resolve/?couponCode=57ECCB221AD03722F409', 'https://www.udemy.com/course/aftereffectsmasterclass/?couponCode=BFDAYFREE', 'https://www.udemy.com/course/financial-accounting-accounting-cycle/?couponCode=6E7898B80DC5DBE51CED', 'https://www.udemy.com/course/xero-accounting-software-2020/?couponCode=97DEA1CF58DFD9060CAE'",
"'https://www.udemy.com/course/time-value-of-money-capital-budgeting-present-value/?couponCode=353099189D7E0DA4964C', 'https://www.udemy.com/course/relevant-costs-managerial-accounting-decisions-scenarios/?couponCode=C6DC7BA10A6B02F0A100', 'https://www.udemy.com/course/manifest-your-dreams-with-eft/?couponCode=MIDWENOV122020', 'https://www.udemy.com/course/how-to-create-a-sold-out-event/?couponCode=SHCAEEXPNOV122020', 'https://www.udemy.com/course/unstoppable-self-confidence-success/?couponCode=USCYKNOV122020', 'https://www.udemy.com/course/blissful-real-estate-investing/?couponCode=BREINOV122020', 'https://www.udemy.com/course/eiq2-customer-service/?couponCode=EIQPPNOV122020', 'https://www.udemy.com/course/yoga-sutras/?couponCode=YSPAYNOV122020', 'https://www.udemy.com/course/learn-css-and-bootstrap-from-scratch/?couponCode=JQUERYNOV2020', 'https://www.udemy.com/course/instructional-design-course/?couponCode=DESIGN10', 'https://www.udemy.com/course/activities-and-tools-used-for-business-iiba-ecba/?couponCode=2E97352EC7857C018678', 'https://www.udemy.com/course/business-analysis-competencies-personal-skills-iiba-ecba/?couponCode=DC87EE0F9CBFA6676C88'",
"'https://bit.ly/38tp6C9', 'https://www.udemy.com/course/productivitycourse/?couponCode=BFDAYFREE', 'https://www.udemy.com/course/procurement-planning-pmi-pmp/?couponCode=6E3511FB76756855B8CA', 'https://www.udemy.com/course/monitor-project-communications-pmi-pmp/?couponCode=B3916C2A9AB97B01E15A', 'https://www.udemy.com/course/management-of-quality-in-operations/?couponCode=A9E44872D5C4CD9E0642', 'https://www.udemy.com/course/security-awareness-for-everyone/?couponCode=7D3DE0D416E938C04EC7', 'https://www.udemy.com/course/how-to-create-video-ads-for-social-media-with-invideo/?couponCode=637FC6A15A01A26AD53F', 'https://www.udemy.com/course/how-to-udemy-course-sell/?couponCode=ENDS11TH', 'https://www.udemy.com/course/google-cloud-professional-data-engineer-get-certified/?couponCode=0AE519024C29A8F1CA81', 'https://www.udemy.com/course/unity2d-temel-c-ve-dogru-kodlama-egitimi/?couponCode=20C23F47D14467D839D4', 'https://www.udemy.com/course/pern-stack-build-a-yelp-clone-postgresexpressreactnode/?couponCode=C3C065AC34DAD1B6D209', 'https://www.udemy.com/course/guitar-switch-chords-effortlessly/?couponCode=B4F5503330F4B7D64801'"]
"""
splitted_links_array = []
count = 1
for i in range(len(udemy_links_array)):
    splitted_links_array.append(udemy_links_array[i].split(","))

print(splitted_links_array[0])


"""for i in range(len(splitted_links_array)):
    links = splitted_links_array[i]
    a=len(links)
    for j in range(a):
        line = links[j].strip().split("'")
        #for k in range(len(line)):
        url = line[1]
        req = requests.get(url, headers)
        soup = BeautifulSoup(req.content, 'html.parser')
        url_body = soup.get_text()
        udemy_formatted_body = url_body.split("\n",5)
        title = udemy_formatted_body[4]
        if '|' in title:
            updated_title = title.split("|")
            print(str(count) + ". " + updated_title[0])
        else:
            print(str(count) + ". " + title)

        print(url)
        print()
        z= z + 1"""